### ISSUE TITLE
[Bug] Announcement mod crashes the game client

### ISSUE THREAD

**Issue by Cornholio777** [data-bomb/Silica#23]
**Describe the bug**
Silica enters a state of "not responding", I believe it's due to the Announcement mod with a certain configuration.

**To Reproduce**
1. Add the Announcement mod to your server.
2. In the configuration file announcments.txt, add 4 lines of announcements.
3. (Optional) Reduce the time between announcements, I chose 180 seconds.
4. Run the client server, wait until all announcements have been announced.
5. Once all announcements have been announced 1 time and it returns to the first line, the game stops responding, soft crash.

**Screenshots**
If applicable, add screenshots to help explain your problem

**Log file**
![{40DDFF96-5A0F-4D60-90C0-F946FFFBF1B9}](https://github.com/data-bomb/Silica/assets/143255018/e2b43b6d-80d9-4bd9-8dbc-82533e34f2dc)
![{E32EF625-CD34-42B0-8BA7-B6A86819727C}](https://github.com/data-bomb/Silica/assets/143255018/5628c865-3d0f-42c9-9cb6-a4a63d0c4400)

Go to your game's root directory. The default is `C:\Program Files(x86)\Steam\steamapps\common\Silica`
Open the `MelonLoader` directory
Find the file called Latest or Latest.log
Include the entire file or relevant portions related to the bug
[Latest.log](https://github.com/data-bomb/Silica/files/13366037/Latest.log)

**Comment by Cornholio777** [comment]
I noticed that "not responding" also happens when I select text in the Melon Loader, once I press enter it returned the game to natural state. Need to test the Announcement thing again...

**Comment by data-bomb** [comment]
@Cornholio777 yes, one of those issues where correlation does not necessarily mean causation. This is one of the downsides of using MelonLoader's console in this way and is a common cause of the game hanging.
