### ISSUE TITLE
[Bug] Defaultunits broken

### ISSUE THREAD

**Issue by Cornholio777** [data-bomb/Silica#25]
**Describe the bug**
After latest changelog, defaultunit mod is broken. First round it works, but on second round, the defaultunits are not reset, so players spawn as Wasps or Rifleman for example at the start of the round.

**To Reproduce**
1. Start server, have mod with my configuration in the log file.
2. Play the game and research tech until you unlock wasps or rifleman
3. Endround.
Now next round the defaultunits are wasps/rifleman at round start already, it should be reset to crab/scout.

**Log file**
Go to your game's root directory. The default is `C:\Program Files(x86)\Steam\steamapps\common\Silica`
Open the `MelonLoader` directory
Find the file called Latest or Latest.log
Include the entire file or relevant portions related to the bug

[Latest_-_Copy.log](https://github.com/data-bomb/Silica/files/13603876/Latest_-_Copy.log)
[Player - Copy.log](https://github.com/data-bomb/Silica/files/13603877/Player.-.Copy.log)

**Comment by data-bomb** [comment]
DefaultUnits has been fixed and Tech Tier 0 is now supported as well as consistent resets after each round
